image: node

stages:
  - test
  - package
  - deploy

# test:
#     stage: test
#     before_script:
#         - yarn install
#     script:
#         - yarn test:e2e

# vulnerabilities check:
#   stage: test
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}
#     policy: push
#     paths:
#       - ./node_modules
#   script:
#     - yarn install
#     - yarn scan

build hermod: &build
  stage: package
  cache:
    key: site-package
    policy: push
    paths:
      - ./dist
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - ./node_modules
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2h20min
    paths:
      - ./dist
  script:
    - yarn build

# deploy to develop: &deploy
#   stage: deploy
#   variables:
#     CNAME: develop-hermod.surge.sh
#     GIT_STRATEGY: none
#   cache:
#     key: site-package
#     policy: pull
#     paths:
#       - ./dist
#   before_script:
#     - yarn global add surge
#   script:
#     - surge --project ./dist --domain ${CNAME}
#   environment:
#     name: develop
#     url: http://${CNAME}
#   only:
#     - develop

# deploy to release: &deploy-release
#   <<: *deploy
#   variables:
#     CNAME: $CI_COMMIT_REF_SLUG.hermod.surge.sh
#   environment:
#     name: review/$CI_COMMIT_REF_SLUG
#     on_stop: turnoff
#   only:
#     - /^release-.*$/

# turnoff:
#   <<: *deploy-release
#   script:
#     - surge teardown ${CNAME}
#   when: manual
#   environment:
#     name: review/$CI_COMMIT_REF_SLUG
#     action: stop

deploy to production:
  image: amazonlinux
  stage: deploy
  variables:
    S3_BUCKET: s3://hermod.s3-website-sa-east-1.amazonaws.com
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
    paths:
      - ./dist
  before_script:
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py
    - pip install awscli --upgrade --user && export PATH=/.local/bin:$PATH
    - aws --version
  script:
    - aws s3 ls ${S3_BUCKET}
    - cd dist && pwd && ls -ltra
    - aws s3 rm ${S3_BUCKET}/ --recursive
    - aws s3 cp . ${S3_BUCKET} --acl public-read --recursive
  environment:
    name: production
    url: http://hermod.s3-website-sa-east-1.amazonaws.com
  only:
    - master
